"""Initial tables

Revision ID: 63106aa1db5f
Revises: 
Create Date: 2026-08-23 22:40:47.003452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63106aa1db5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_table('bank_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('utr', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_records_id'), 'bank_records', ['id'], unique=False)
    op.create_index(op.f('ix_bank_records_reference'), 'bank_records', ['reference'], unique=False)
    op.create_index(op.f('ix_bank_records_utr'), 'bank_records', ['utr'], unique=False)
    op.create_table('investigation_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('candidate_matches', sa.JSON(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_cases_case_type'), 'investigation_cases', ['case_type'], unique=False)
    op.create_index(op.f('ix_investigation_cases_id'), 'investigation_cases', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_cases_status'), 'investigation_cases', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_reference', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('candidate_record_id', sa.String(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_results_candidate_record_id'), 'reconciliation_results', ['candidate_record_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_id'), 'reconciliation_results', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_source_record_id'), 'reconciliation_results', ['source_record_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fees', sa.Integer(), nullable=True),
    sa.Column('tax', sa.Integer(), nullable=True),
    sa.Column('utr', sa.String(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_references', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_id'), 'settlements', ['id'], unique=False)
    op.create_index(op.f('ix_settlements_status'), 'settlements', ['status'], unique=False)
    op.create_index(op.f('ix_settlements_utr'), 'settlements', ['utr'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_settlements_utr'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_reconciliation_results_source_record_id'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_id'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_candidate_record_id'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_investigation_cases_status'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_id'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_case_type'), table_name='investigation_cases')
    op.drop_table('investigation_cases')
    op.drop_index(op.f('ix_bank_records_utr'), table_name='bank_records')
    op.drop_index(op.f('ix_bank_records_reference'), table_name='bank_records')
    op.drop_index(op.f('ix_bank_records_id'), table_name='bank_records')
    op.drop_table('bank_records')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
